-- Sri Lankan Hospital Medicine Database
-- Based on the National Medicines Regulatory Authority (NMRA) Sri Lanka essential medicines list
-- Includes medicines commonly available in government hospitals

INSERT INTO medicines (generic_name, brand_name, strength, form, manufacturer, category) VALUES
  -- Cardiovascular
  ('Amlodipine', 'Amlopin', '5mg', 'tablet', 'State Pharmaceuticals Corporation', 'Cardiovascular'),
  ('Amlodipine', 'Amlopin', '10mg', 'tablet', 'State Pharmaceuticals Corporation', 'Cardiovascular'),
  ('Atenolol', 'Atecard', '50mg', 'tablet', 'State Pharmaceuticals Corporation', 'Cardiovascular'),
  ('Atenolol', 'Atecard', '100mg', 'tablet', 'State Pharmaceuticals Corporation', 'Cardiovascular'),
  ('Enalapril', 'Envas', '5mg', 'tablet', 'State Pharmaceuticals Corporation', 'Cardiovascular'),
  ('Enalapril', 'Envas', '10mg', 'tablet', 'State Pharmaceuticals Corporation', 'Cardiovascular'),
  ('Losartan', 'Losar', '50mg', 'tablet', 'Astron Ltd', 'Cardiovascular'),
  ('Losartan', 'Losar', '100mg', 'tablet', 'Astron Ltd', 'Cardiovascular'),
  ('Metoprolol', 'Betaloc', '50mg', 'tablet', 'AstraZeneca', 'Cardiovascular'),
  ('Metoprolol', 'Betaloc', '100mg', 'tablet', 'AstraZeneca', 'Cardiovascular'),
  ('Nifedipine', 'Adalat', '20mg', 'tablet', 'Bayer', 'Cardiovascular'),
  ('Aspirin', 'Aspirin', '75mg', 'tablet', 'State Pharmaceuticals Corporation', 'Cardiovascular'),
  ('Aspirin', 'Aspirin', '300mg', 'tablet', 'State Pharmaceuticals Corporation', 'Cardiovascular'),
  ('Clopidogrel', 'Clopivas', '75mg', 'tablet', 'Cipla', 'Cardiovascular'),
  ('Warfarin', 'Warin', '1mg', 'tablet', 'State Pharmaceuticals Corporation', 'Cardiovascular'),
  ('Warfarin', 'Warin', '3mg', 'tablet', 'State Pharmaceuticals Corporation', 'Cardiovascular'),
  ('Warfarin', 'Warin', '5mg', 'tablet', 'State Pharmaceuticals Corporation', 'Cardiovascular'),
  ('Digoxin', 'Lanoxin', '0.25mg', 'tablet', 'GlaxoSmithKline', 'Cardiovascular'),
  ('Furosemide', 'Lasix', '40mg', 'tablet', 'Sanofi', 'Cardiovascular'),
  ('Furosemide', 'Lasix', '20mg/2ml', 'injection', 'Sanofi', 'Cardiovascular'),
  ('Hydrochlorothiazide', 'HCT', '25mg', 'tablet', 'State Pharmaceuticals Corporation', 'Cardiovascular'),
  ('Spironolactone', 'Aldactone', '25mg', 'tablet', 'Pfizer', 'Cardiovascular'),
  ('Simvastatin', 'Simvotin', '20mg', 'tablet', 'State Pharmaceuticals Corporation', 'Cardiovascular'),
  ('Simvastatin', 'Simvotin', '40mg', 'tablet', 'State Pharmaceuticals Corporation', 'Cardiovascular'),
  ('Atorvastatin', 'Atorlip', '10mg', 'tablet', 'Cipla', 'Cardiovascular'),
  ('Atorvastatin', 'Atorlip', '20mg', 'tablet', 'Cipla', 'Cardiovascular'),
  ('Atorvastatin', 'Atorlip', '40mg', 'tablet', 'Cipla', 'Cardiovascular'),
  ('Isosorbide Dinitrate', 'Isordil', '10mg', 'tablet', 'Wyeth', 'Cardiovascular'),
  ('Glyceryl Trinitrate', 'GTN', '0.5mg', 'tablet', 'State Pharmaceuticals Corporation', 'Cardiovascular'),
  ('Prazosin', 'Minipress', '1mg', 'tablet', 'Pfizer', 'Cardiovascular'),

  -- Analgesics & Anti-inflammatory
  ('Paracetamol', 'Panadol', '500mg', 'tablet', 'GlaxoSmithKline', 'Analgesics'),
  ('Paracetamol', 'Panadol', '120mg/5ml', 'syrup', 'GlaxoSmithKline', 'Analgesics'),
  ('Paracetamol', 'Calpol', '250mg/5ml', 'suspension', 'GlaxoSmithKline', 'Analgesics'),
  ('Ibuprofen', 'Brufen', '200mg', 'tablet', 'Abbott', 'Analgesics'),
  ('Ibuprofen', 'Brufen', '400mg', 'tablet', 'Abbott', 'Analgesics'),
  ('Diclofenac Sodium', 'Voltaren', '50mg', 'tablet', 'Novartis', 'Analgesics'),
  ('Diclofenac Sodium', 'Voltaren', '75mg/3ml', 'injection', 'Novartis', 'Analgesics'),
  ('Diclofenac Sodium', 'Voltaren', '1%', 'gel', 'Novartis', 'Analgesics'),
  ('Naproxen', 'Naprosyn', '250mg', 'tablet', 'Roche', 'Analgesics'),
  ('Naproxen', 'Naprosyn', '500mg', 'tablet', 'Roche', 'Analgesics'),
  ('Mefenamic Acid', 'Ponstan', '250mg', 'capsule', 'Pfizer', 'Analgesics'),
  ('Mefenamic Acid', 'Ponstan', '500mg', 'tablet', 'Pfizer', 'Analgesics'),
  ('Tramadol', 'Tramadol', '50mg', 'capsule', 'State Pharmaceuticals Corporation', 'Analgesics'),
  ('Morphine Sulfate', 'Morphine', '10mg', 'tablet', 'State Pharmaceuticals Corporation', 'Analgesics'),
  ('Morphine Sulfate', 'Morphine', '10mg/ml', 'injection', 'State Pharmaceuticals Corporation', 'Analgesics'),
  ('Codeine Phosphate', 'Codeine', '30mg', 'tablet', 'State Pharmaceuticals Corporation', 'Analgesics'),

  -- Antibiotics
  ('Amoxicillin', 'Amoxil', '250mg', 'capsule', 'State Pharmaceuticals Corporation', 'Antibiotics'),
  ('Amoxicillin', 'Amoxil', '500mg', 'capsule', 'State Pharmaceuticals Corporation', 'Antibiotics'),
  ('Amoxicillin', 'Amoxil', '125mg/5ml', 'suspension', 'State Pharmaceuticals Corporation', 'Antibiotics'),
  ('Amoxicillin/Clavulanic Acid', 'Augmentin', '625mg', 'tablet', 'GlaxoSmithKline', 'Antibiotics'),
  ('Amoxicillin/Clavulanic Acid', 'Augmentin', '1g', 'tablet', 'GlaxoSmithKline', 'Antibiotics'),
  ('Azithromycin', 'Zithromax', '250mg', 'tablet', 'Pfizer', 'Antibiotics'),
  ('Azithromycin', 'Zithromax', '500mg', 'tablet', 'Pfizer', 'Antibiotics'),
  ('Cephalexin', 'Cefalin', '250mg', 'capsule', 'State Pharmaceuticals Corporation', 'Antibiotics'),
  ('Cephalexin', 'Cefalin', '500mg', 'capsule', 'State Pharmaceuticals Corporation', 'Antibiotics'),
  ('Cefuroxime', 'Zinnat', '250mg', 'tablet', 'GlaxoSmithKline', 'Antibiotics'),
  ('Cefuroxime', 'Zinnat', '500mg', 'tablet', 'GlaxoSmithKline', 'Antibiotics'),
  ('Ceftriaxone', 'Ceftriaxone', '1g', 'injection', 'State Pharmaceuticals Corporation', 'Antibiotics'),
  ('Ciprofloxacin', 'Ciprobay', '250mg', 'tablet', 'Bayer', 'Antibiotics'),
  ('Ciprofloxacin', 'Ciprobay', '500mg', 'tablet', 'Bayer', 'Antibiotics'),
  ('Cloxacillin', 'Cloxacillin', '250mg', 'capsule', 'State Pharmaceuticals Corporation', 'Antibiotics'),
  ('Cloxacillin', 'Cloxacillin', '500mg', 'capsule', 'State Pharmaceuticals Corporation', 'Antibiotics'),
  ('Co-trimoxazole', 'Bactrim', '480mg', 'tablet', 'Roche', 'Antibiotics'),
  ('Doxycycline', 'Doxycycline', '100mg', 'capsule', 'State Pharmaceuticals Corporation', 'Antibiotics'),
  ('Erythromycin', 'Erythromycin', '250mg', 'tablet', 'State Pharmaceuticals Corporation', 'Antibiotics'),
  ('Erythromycin', 'Erythromycin', '500mg', 'tablet', 'State Pharmaceuticals Corporation', 'Antibiotics'),
  ('Metronidazole', 'Flagyl', '200mg', 'tablet', 'Sanofi', 'Antibiotics'),
  ('Metronidazole', 'Flagyl', '400mg', 'tablet', 'Sanofi', 'Antibiotics'),
  ('Nitrofurantoin', 'Macrobid', '100mg', 'capsule', 'Procter & Gamble', 'Antibiotics'),
  ('Penicillin V', 'Pen V', '250mg', 'tablet', 'State Pharmaceuticals Corporation', 'Antibiotics'),
  ('Gentamicin', 'Gentamicin', '80mg/2ml', 'injection', 'State Pharmaceuticals Corporation', 'Antibiotics'),

  -- Diabetes
  ('Metformin', 'Glucophage', '500mg', 'tablet', 'Merck', 'Diabetes'),
  ('Metformin', 'Glucophage', '850mg', 'tablet', 'Merck', 'Diabetes'),
  ('Metformin', 'Glucophage', '1000mg', 'tablet', 'Merck', 'Diabetes'),
  ('Glibenclamide', 'Daonil', '5mg', 'tablet', 'Sanofi', 'Diabetes'),
  ('Gliclazide', 'Diamicron', '80mg', 'tablet', 'Servier', 'Diabetes'),
  ('Gliclazide', 'Diamicron MR', '30mg', 'tablet', 'Servier', 'Diabetes'),
  ('Glimepiride', 'Amaryl', '1mg', 'tablet', 'Sanofi', 'Diabetes'),
  ('Glimepiride', 'Amaryl', '2mg', 'tablet', 'Sanofi', 'Diabetes'),
  ('Insulin (Soluble)', 'Actrapid', '100IU/ml', 'injection', 'Novo Nordisk', 'Diabetes'),
  ('Insulin (Isophane)', 'Insulatard', '100IU/ml', 'injection', 'Novo Nordisk', 'Diabetes'),
  ('Insulin (Mixed)', 'Mixtard 30', '100IU/ml', 'injection', 'Novo Nordisk', 'Diabetes'),
  ('Sitagliptin', 'Januvia', '100mg', 'tablet', 'MSD', 'Diabetes'),

  -- Respiratory
  ('Salbutamol', 'Ventolin', '100mcg/dose', 'inhaler', 'GlaxoSmithKline', 'Respiratory'),
  ('Salbutamol', 'Ventolin', '2mg/5ml', 'syrup', 'GlaxoSmithKline', 'Respiratory'),
  ('Salbutamol', 'Ventolin', '4mg', 'tablet', 'GlaxoSmithKline', 'Respiratory'),
  ('Beclomethasone', 'Becotide', '200mcg/dose', 'inhaler', 'GlaxoSmithKline', 'Respiratory'),
  ('Budesonide', 'Pulmicort', '200mcg/dose', 'inhaler', 'AstraZeneca', 'Respiratory'),
  ('Ipratropium Bromide', 'Atrovent', '20mcg/dose', 'inhaler', 'Boehringer Ingelheim', 'Respiratory'),
  ('Theophylline', 'Theo-Dur', '200mg', 'tablet', 'AstraZeneca', 'Respiratory'),
  ('Montelukast', 'Singulair', '10mg', 'tablet', 'MSD', 'Respiratory'),
  ('Prednisolone', 'Prednisolone', '5mg', 'tablet', 'State Pharmaceuticals Corporation', 'Respiratory'),
  ('Dextromethorphan', 'Benylin DM', '15mg/5ml', 'syrup', 'Johnson & Johnson', 'Respiratory'),
  ('Cetirizine', 'Zyrtec', '10mg', 'tablet', 'UCB', 'Respiratory'),
  ('Chlorpheniramine', 'Piriton', '4mg', 'tablet', 'GlaxoSmithKline', 'Respiratory'),
  ('Chlorpheniramine', 'Piriton', '2mg/5ml', 'syrup', 'GlaxoSmithKline', 'Respiratory'),
  ('Loratadine', 'Claritin', '10mg', 'tablet', 'Bayer', 'Respiratory'),
  ('Fexofenadine', 'Telfast', '120mg', 'tablet', 'Sanofi', 'Respiratory'),
  ('Fexofenadine', 'Telfast', '180mg', 'tablet', 'Sanofi', 'Respiratory'),

  -- Gastrointestinal
  ('Omeprazole', 'Losec', '20mg', 'capsule', 'AstraZeneca', 'Gastrointestinal'),
  ('Omeprazole', 'Losec', '40mg', 'capsule', 'AstraZeneca', 'Gastrointestinal'),
  ('Lansoprazole', 'Prevacid', '30mg', 'capsule', 'Takeda', 'Gastrointestinal'),
  ('Pantoprazole', 'Pantocid', '40mg', 'tablet', 'Sun Pharma', 'Gastrointestinal'),
  ('Ranitidine', 'Zantac', '150mg', 'tablet', 'GlaxoSmithKline', 'Gastrointestinal'),
  ('Domperidone', 'Motilium', '10mg', 'tablet', 'Janssen', 'Gastrointestinal'),
  ('Metoclopramide', 'Maxolon', '10mg', 'tablet', 'Sanofi', 'Gastrointestinal'),
  ('Hyoscine Butylbromide', 'Buscopan', '10mg', 'tablet', 'Boehringer Ingelheim', 'Gastrointestinal'),
  ('Loperamide', 'Imodium', '2mg', 'capsule', 'Janssen', 'Gastrointestinal'),
  ('Oral Rehydration Salts', 'Jeevani', '1 sachet', 'powder', 'State Pharmaceuticals Corporation', 'Gastrointestinal'),
  ('Lactulose', 'Duphalac', '10g/15ml', 'syrup', 'Abbott', 'Gastrointestinal'),
  ('Bisacodyl', 'Dulcolax', '5mg', 'tablet', 'Boehringer Ingelheim', 'Gastrointestinal'),
  ('Antacid (Al/Mg hydroxide)', 'Maalox', '500mg', 'tablet', 'Sanofi', 'Gastrointestinal'),

  -- Neurological / Psychiatric
  ('Gabapentin', 'Neurontin', '300mg', 'capsule', 'Pfizer', 'Neurological'),
  ('Gabapentin', 'Neurontin', '400mg', 'capsule', 'Pfizer', 'Neurological'),
  ('Carbamazepine', 'Tegretol', '200mg', 'tablet', 'Novartis', 'Neurological'),
  ('Sodium Valproate', 'Epilim', '200mg', 'tablet', 'Sanofi', 'Neurological'),
  ('Sodium Valproate', 'Epilim', '500mg', 'tablet', 'Sanofi', 'Neurological'),
  ('Phenytoin', 'Dilantin', '100mg', 'capsule', 'Pfizer', 'Neurological'),
  ('Levodopa/Carbidopa', 'Sinemet', '250mg/25mg', 'tablet', 'MSD', 'Neurological'),
  ('Amitriptyline', 'Tryptanol', '25mg', 'tablet', 'MSD', 'Neurological'),
  ('Fluoxetine', 'Prozac', '20mg', 'capsule', 'Lilly', 'Neurological'),
  ('Sertraline', 'Zoloft', '50mg', 'tablet', 'Pfizer', 'Neurological'),
  ('Diazepam', 'Valium', '5mg', 'tablet', 'Roche', 'Neurological'),
  ('Diazepam', 'Valium', '10mg/2ml', 'injection', 'Roche', 'Neurological'),
  ('Chlorpromazine', 'Largactil', '100mg', 'tablet', 'Sanofi', 'Neurological'),
  ('Haloperidol', 'Serenace', '5mg', 'tablet', 'Searle', 'Neurological'),
  ('Risperidone', 'Risperdal', '2mg', 'tablet', 'Janssen', 'Neurological'),
  ('Sumatriptan', 'Imigran', '50mg', 'tablet', 'GlaxoSmithKline', 'Neurological'),

  -- Dermatological
  ('Betamethasone', 'Betnovate', '0.1%', 'cream', 'GlaxoSmithKline', 'Dermatological'),
  ('Hydrocortisone', 'Hydrocortisone', '1%', 'cream', 'State Pharmaceuticals Corporation', 'Dermatological'),
  ('Clotrimazole', 'Canesten', '1%', 'cream', 'Bayer', 'Dermatological'),
  ('Miconazole', 'Daktarin', '2%', 'cream', 'Janssen', 'Dermatological'),
  ('Mupirocin', 'Bactroban', '2%', 'ointment', 'GlaxoSmithKline', 'Dermatological'),
  ('Permethrin', 'Lyclear', '5%', 'cream', 'State Pharmaceuticals Corporation', 'Dermatological'),
  ('Calamine', 'Calamine Lotion', '15%', 'solution', 'State Pharmaceuticals Corporation', 'Dermatological'),
  ('Silver Sulfadiazine', 'Silverex', '1%', 'cream', 'State Pharmaceuticals Corporation', 'Dermatological'),

  -- Supplements & Vitamins
  ('Ferrous Sulfate', 'Fefol', '200mg', 'tablet', 'State Pharmaceuticals Corporation', 'Supplements'),
  ('Ferrous Fumarate', 'Ferrograd', '322mg', 'tablet', 'Abbott', 'Supplements'),
  ('Folic Acid', 'Folic Acid', '5mg', 'tablet', 'State Pharmaceuticals Corporation', 'Supplements'),
  ('Calcium Carbonate', 'Caltrate', '500mg', 'tablet', 'Pfizer', 'Supplements'),
  ('Calcium + Vitamin D', 'Cal-D', '500mg/250IU', 'tablet', 'State Pharmaceuticals Corporation', 'Supplements'),
  ('Vitamin B Complex', 'Becosules', '1 capsule', 'capsule', 'Pfizer', 'Supplements'),
  ('Vitamin C', 'Cevital', '500mg', 'tablet', 'State Pharmaceuticals Corporation', 'Supplements'),
  ('Multivitamin', 'Multivitamin', '1 tablet', 'tablet', 'State Pharmaceuticals Corporation', 'Supplements'),
  ('Zinc Sulfate', 'Zinc', '20mg', 'tablet', 'State Pharmaceuticals Corporation', 'Supplements'),

  -- Endocrine / Thyroid
  ('Levothyroxine', 'Eltroxin', '50mcg', 'tablet', 'GlaxoSmithKline', 'Endocrine'),
  ('Levothyroxine', 'Eltroxin', '100mcg', 'tablet', 'GlaxoSmithKline', 'Endocrine'),
  ('Carbimazole', 'Neo-Mercazole', '5mg', 'tablet', 'Abbott', 'Endocrine'),
  ('Prednisolone', 'Prednisolone', '5mg', 'tablet', 'State Pharmaceuticals Corporation', 'Endocrine'),
  ('Dexamethasone', 'Dexamethasone', '0.5mg', 'tablet', 'State Pharmaceuticals Corporation', 'Endocrine'),
  ('Dexamethasone', 'Dexamethasone', '4mg/ml', 'injection', 'State Pharmaceuticals Corporation', 'Endocrine'),

  -- Musculoskeletal
  ('Allopurinol', 'Zyloric', '100mg', 'tablet', 'GlaxoSmithKline', 'Musculoskeletal'),
  ('Allopurinol', 'Zyloric', '300mg', 'tablet', 'GlaxoSmithKline', 'Musculoskeletal'),
  ('Colchicine', 'Colchicine', '0.5mg', 'tablet', 'State Pharmaceuticals Corporation', 'Musculoskeletal'),
  ('Methotrexate', 'Methotrexate', '2.5mg', 'tablet', 'Pfizer', 'Musculoskeletal'),
  ('Hydroxychloroquine', 'Plaquenil', '200mg', 'tablet', 'Sanofi', 'Musculoskeletal'),
  ('Piroxicam', 'Feldene', '20mg', 'capsule', 'Pfizer', 'Musculoskeletal'),

  -- Ophthalmological
  ('Chloramphenicol', 'Chloramphenicol', '0.5%', 'drops', 'State Pharmaceuticals Corporation', 'Ophthalmological'),
  ('Ciprofloxacin', 'Ciloxan', '0.3%', 'drops', 'Novartis', 'Ophthalmological'),
  ('Timolol', 'Timoptol', '0.5%', 'drops', 'MSD', 'Ophthalmological'),
  ('Artificial Tears', 'Tears Naturale', '0.1%', 'drops', 'Alcon', 'Ophthalmological'),

  -- Antiparasitic
  ('Albendazole', 'Zentel', '400mg', 'tablet', 'GlaxoSmithKline', 'Antiparasitic'),
  ('Mebendazole', 'Vermox', '100mg', 'tablet', 'Janssen', 'Antiparasitic'),

  -- Others
  ('Adrenaline (Epinephrine)', 'Adrenaline', '1mg/ml', 'injection', 'State Pharmaceuticals Corporation', 'Emergency'),
  ('Atropine', 'Atropine', '0.6mg/ml', 'injection', 'State Pharmaceuticals Corporation', 'Emergency'),
  ('Hydrocortisone', 'Solu-Cortef', '100mg', 'injection', 'Pfizer', 'Emergency'),
  ('Promethazine', 'Phenergan', '25mg', 'tablet', 'Sanofi', 'Antihistamine'),
  ('Promethazine', 'Phenergan', '25mg/ml', 'injection', 'Sanofi', 'Antihistamine'),
  ('Methotrexate', 'Methotrexate', '15mg/ml', 'injection', 'Pfizer', 'Immunosuppressant'),
  ('Tranexamic Acid', 'Cyklokapron', '500mg', 'tablet', 'Pfizer', 'Haematological'),
  ('Heparin', 'Heparin', '5000IU/ml', 'injection', 'State Pharmaceuticals Corporation', 'Haematological'),
  ('Enoxaparin', 'Clexane', '40mg/0.4ml', 'injection', 'Sanofi', 'Haematological');
