/**
 * Script to create and upload dummy PDF files for all seeded lab reports
 * This will update lab reports that don't have file_key to include S3-stored PDFs
 */

const db = require('../src/config/database');
const { S3Client, PutObjectCommand } = require('@aws-sdk/client-s3');
const crypto = require('crypto');
const path = require('path');
const config = require('../src/config');

// Initialize S3 client
const s3 = new S3Client({
  region: config.s3.region,
  credentials: {
    accessKeyId: config.s3.accessKeyId,
    secretAccessKey: config.s3.secretAccessKey,
  },
});

/**
 * Generate a minimal PDF file with test name and result
 * This creates a valid PDF structure with basic text content
 */
function generatePDF(testName, result, notes, reportDate) {
  const content = `
Lab Report: ${testName}
Date: ${new Date(reportDate).toLocaleDateString()}
${'='.repeat(60)}

RESULTS:
${result || 'No result data available'}

${notes ? `NOTES:\n${notes}` : ''}

${'='.repeat(60)}
Generated by MedEase Hospital Management System
  `.trim();

  // Create a minimal valid PDF structure
  const pdfContent = `%PDF-1.4
1 0 obj
<<
/Type /Catalog
/Pages 2 0 R
>>
endobj
2 0 obj
<<
/Type /Pages
/Kids [3 0 R]
/Count 1
>>
endobj
3 0 obj
<<
/Type /Page
/Parent 2 0 R
/MediaBox [0 0 612 792]
/Contents 4 0 R
/Resources <<
/Font <<
/F1 <<
/Type /Font
/Subtype /Type1
/BaseFont /Courier
>>
>>
>>
>>
endobj
4 0 obj
<<
/Length ${content.length + 50}
>>
stream
BT
/F1 10 Tf
50 750 Td
${content.split('\n').map((line, i) => `(${line.replace(/[()\\]/g, '\\$&')}) Tj\n0 -12 Td`).join('\n')}
ET
endstream
endobj
xref
0 5
0000000000 65535 f
0000000009 00000 n
0000000058 00000 n
0000000115 00000 n
0000000317 00000 n
trailer
<<
/Size 5
/Root 1 0 R
>>
startxref
${400 + content.length}
%%EOF`;

  return Buffer.from(pdfContent, 'utf-8');
}

/**
 * Upload PDF to S3
 */
async function uploadToS3(buffer, patientId, fileName) {
  const ext = '.pdf';
  const hash = crypto.randomBytes(16).toString('hex');
  const key = `lab-reports/${patientId}/${hash}${ext}`;

  await s3.send(
    new PutObjectCommand({
      Bucket: config.s3.bucket,
      Key: key,
      Body: buffer,
      ContentType: 'application/pdf',
    })
  );

  return key;
}

/**
 * Main function
 */
async function seedLabReportFiles() {
  let client;
  try {
    console.log('🔍 Fetching lab reports without files...');

    // Get all lab reports without files
    const result = await db.query(
      `SELECT id, patient_id, test_name, result, notes, report_date
       FROM lab_reports
       WHERE file_key IS NULL
       ORDER BY report_date ASC`
    );

    const reports = result.rows;
    console.log(`📋 Found ${reports.length} lab reports without files`);

    if (reports.length === 0) {
      console.log('✅ All lab reports already have files!');
      return;
    }

    client = await db.getClient();

    let successCount = 0;
    let errorCount = 0;

    for (const report of reports) {
      try {
        console.log(`\n📄 Processing: ${report.test_name} (Patient: ${report.patient_id})`);

        // Generate PDF
        const pdfBuffer = generatePDF(
          report.test_name,
          report.result,
          report.notes,
          report.report_date
        );

        // Upload to S3
        const fileName = `${report.test_name.replace(/[^a-zA-Z0-9]/g, '_')}_Report.pdf`;
        const fileKey = await uploadToS3(pdfBuffer, report.patient_id, fileName);

        console.log(`   ✓ Uploaded to S3: ${fileKey}`);

        // Update database
        await client.query(
          `UPDATE lab_reports
           SET file_key = $1, file_name = $2
           WHERE id = $3`,
          [fileKey, fileName, report.id]
        );

        console.log(`   ✓ Updated database record`);
        successCount++;
      } catch (err) {
        console.error(`   ✗ Error processing report ${report.id}:`, err.message);
        errorCount++;
      }
    }

    console.log(`\n${'='.repeat(60)}`);
    console.log(`✅ Success: ${successCount} lab reports`);
    if (errorCount > 0) {
      console.log(`❌ Failed: ${errorCount} lab reports`);
    }
    console.log(`${'='.repeat(60)}\n`);
  } catch (err) {
    console.error('❌ Fatal error:', err);
    throw err;
  } finally {
    if (client) {
      client.release();
    }
  }
}

// Run the script
if (require.main === module) {
  seedLabReportFiles()
    .then(() => {
      console.log('✅ Script completed successfully');
      process.exit(0);
    })
    .catch((err) => {
      console.error('❌ Script failed:', err);
      process.exit(1);
    });
}

module.exports = { seedLabReportFiles };
