import {
  Bell,
  Calendar,
  Pill,
  Beaker,
  AlertCircle,
  CheckCircle,
  Clock,
  FileText,
  Heart,
  Stethoscope,
  Activity,
  BadgeAlert,
  Package,
  User,
  TrendingUp,
  Shield,
  MessageSquare,
  Eye,
  Trash2,
} from 'lucide-react';

export const NOTIFICATION_TYPES = {
  appointment_scheduled: {
    label: 'Appointment Scheduled',
    icon: Calendar,
    color: 'blue',
    bgColor: 'bg-blue-50',
    borderColor: 'border-blue-200',
    textColor: 'text-blue-600',
  },
  appointment_cancelled: {
    label: 'Appointment Cancelled',
    icon: AlertCircle,
    color: 'red',
    bgColor: 'bg-red-50',
    borderColor: 'border-red-200',
    textColor: 'text-red-600',
  },
  appointment_reminder: {
    label: 'Appointment Reminder',
    icon: Clock,
    color: 'orange',
    bgColor: 'bg-orange-50',
    borderColor: 'border-orange-200',
    textColor: 'text-orange-600',
  },
  appointment_no_show: {
    label: 'No Show Recorded',
    icon: AlertCircle,
    color: 'red',
    bgColor: 'bg-red-50',
    borderColor: 'border-red-200',
    textColor: 'text-red-600',
  },
  prescription_created: {
    label: 'Prescription Created',
    icon: Pill,
    color: 'green',
    bgColor: 'bg-green-50',
    borderColor: 'border-green-200',
    textColor: 'text-green-600',
  },
  prescription_dispensed: {
    label: 'Prescription Dispensed',
    icon: Pill,
    color: 'green',
    bgColor: 'bg-green-50',
    borderColor: 'border-green-200',
    textColor: 'text-green-600',
  },
  refill_requested: {
    label: 'Refill Requested',
    icon: Package,
    color: 'yellow',
    bgColor: 'bg-yellow-50',
    borderColor: 'border-yellow-200',
    textColor: 'text-yellow-600',
  },
  refill_approved: {
    label: 'Refill Approved',
    icon: CheckCircle,
    color: 'green',
    bgColor: 'bg-green-50',
    borderColor: 'border-green-200',
    textColor: 'text-green-600',
  },
  refill_denied: {
    label: 'Refill Denied',
    icon: AlertCircle,
    color: 'red',
    bgColor: 'bg-red-50',
    borderColor: 'border-red-200',
    textColor: 'text-red-600',
  },
  lab_report_ready: {
    label: 'Lab Report Ready',
    icon: Beaker,
    color: 'purple',
    bgColor: 'bg-purple-50',
    borderColor: 'border-purple-200',
    textColor: 'text-purple-600',
  },
  lab_test_requested: {
    label: 'Lab Test Requested',
    icon: Beaker,
    color: 'purple',
    bgColor: 'bg-purple-50',
    borderColor: 'border-purple-200',
    textColor: 'text-purple-600',
  },
  medical_record_created: {
    label: 'Medical Record Created',
    icon: FileText,
    color: 'indigo',
    bgColor: 'bg-indigo-50',
    borderColor: 'border-indigo-200',
    textColor: 'text-indigo-600',
  },
  document_uploaded: {
    label: 'Document Uploaded',
    icon: FileText,
    color: 'indigo',
    bgColor: 'bg-indigo-50',
    borderColor: 'border-indigo-200',
    textColor: 'text-indigo-600',
  },
  feedback_received: {
    label: 'Feedback Received',
    icon: MessageSquare,
    color: 'cyan',
    bgColor: 'bg-cyan-50',
    borderColor: 'border-cyan-200',
    textColor: 'text-cyan-600',
  },
  waitlist_joined: {
    label: 'Added to Waitlist',
    icon: User,
    color: 'slate',
    bgColor: 'bg-slate-50',
    borderColor: 'border-slate-200',
    textColor: 'text-slate-600',
  },
  waitlist_slot_available: {
    label: 'Waitlist Slot Available',
    icon: CheckCircle,
    color: 'green',
    bgColor: 'bg-green-50',
    borderColor: 'border-green-200',
    textColor: 'text-green-600',
  },
  waitlist_cancelled: {
    label: 'Waitlist Cancelled',
    icon: AlertCircle,
    color: 'red',
    bgColor: 'bg-red-50',
    borderColor: 'border-red-200',
    textColor: 'text-red-600',
  },
  system: {
    label: 'System Alert',
    icon: Shield,
    color: 'gray',
    bgColor: 'bg-gray-50',
    borderColor: 'border-gray-200',
    textColor: 'text-gray-600',
  },
  vaccination_recorded: {
    label: 'Vaccination Recorded',
    icon: Heart,
    color: 'rose',
    bgColor: 'bg-rose-50',
    borderColor: 'border-rose-200',
    textColor: 'text-rose-600',
  },
  vital_alert: {
    label: 'Vital Alert',
    icon: Activity,
    color: 'red',
    bgColor: 'bg-red-50',
    borderColor: 'border-red-200',
    textColor: 'text-red-600',
  },
};

export const getNotificationConfig = (type) => {
  return NOTIFICATION_TYPES[type] || NOTIFICATION_TYPES.system;
};

export const FILTER_OPTIONS = {
  ALL: 'all',
  READ: 'read',
  UNREAD: 'unread',
};

export const SORT_OPTIONS = {
  RECENT: '-created_at',
  OLDEST: 'created_at',
  UNREAD_FIRST: 'unread_first',
};

export const PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 10,
  LIMITS: [10, 25, 50],
};
